[VERSION_CFG]
VERSION = 'V2025.4'
AUTHOR = '一一风和橘'

[BIN_CFG]
PATH_CWEBP = "./bin/cwebp.exe"
PATH_EXIFTOOL = "./bin/exiftool.exe"

[FONTS_CFG]
FONT_LATO = "./sources/Fonts/Lato-Italic.ttf"
FONT_MONACO = "./sources/Fonts/MONACO.TTF"
FONT_MPLUS = "./sources/Fonts/MPLUS1p-Regular.ttf"
FONT_NOTO_JP = "./sources/Fonts/NotoSansJP-Regular.ttf"
FONT_NOTO_SC = "./sources/Fonts/NotoSerifSC-Regular.otf"

[LOGO_CFG]
LOGO_FUJIFILM = "./sources/Logo/Fujifilm.png"
LOGO_FUJIFILM_PURE = "./sources/Logo/Fujifilm_Pure.png"
LOGO_SONY = "./sources/Logo/Sony.png"
LOGO_SONY_PURE = "./sources/Logo/Sony_Pure.png"

[APP_CFG]
THEME = "DARK"
QUALITY_INIT = 100
MAX_WORKERS = 8