# Same as Black.
line-length = 120
indent-width = 4
select = [# 选择的规则
    "F",
    "E",
    "I",
    "N",
    "W",
    "PERF",
    "UP",
    "C90",
    #    "D",
    "YTT",
    #    "ANN",
    "ASYNC",
    #    "S", # bandit
    "BLE", # 盲目捕捉异常
    "FBT", # bool
    "B", # bugbear
    "A", # 内置
    "COM", # 尾随逗号
    "CPY", # 版权声明
    "C4", #生成器
    "EM", #异常
    "EXE", # 执行
    #    "FA", # 未来注释
    "ISC", # 字符串链接
    "ICN", # 导入约定
    "LOG", #日志
    "G", # 日志格式
    "INP", # init
    "T20", # print
    "PYI", # pyi
    "PT", # pytest-style
    "Q", # quotes
    "RSE", # raise
    "RET", # return
    "SLF", # 私有成员
    "SLOT", # 槽
    "SIM", # simplify
    "TID", # 引入检查
    "TC", # 类型检查
    "INT", # print相关
    "ARG", # 未使用
    "PTH", # os.path相关
    "DTZ", # datetime
    "TD", # TODO标记
    "FIX", # fixme
    "PL", # pylint
    "NPY", # numpy规则
    "DOC", # 文档规则
    "TRY", # try规则
]
ignore = ["PLR0913", "B019", "PLW2901", "N999", "DTZ007", "DTZ005","T201"]

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"